### ISSUE TITLE
UI controls alignment

### ISSUE THREAD

**Issue by Nico-Duduf** [RxLaboratory/DuAEF_Duik#243]
alignment of elements as most are centered, but some are aligned left..? ;) And the top menu is aligned right atm.

**Comment by reneandritsch** [comment]
Dear Nicolas,

I just saw that were also thinking about the alignment in early stages. I would also like to propose an aligned approach to visually streamline the UI. I think it will be easier to read and even quicker to select items.

![Left_aligned](https://user-images.githubusercontent.com/38455050/55648950-eef80300-57e1-11e9-8e40-b1a0f59b2260.png)

**Comment by Nico-Duduf** [comment]
I've made a lot of attempts for this, and still have to find a workaround, scriptUI lacks a lot of modern options for responsive panels...
Or finally build a new UI using CEP and not scriptUI, which I never had time to
