### ISSUE TITLE
Question: Structures naming convention with “right” and ”left” instead of 1 and 2?

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/DuAEF_Duik#279]
# Feature Request
Dear Nicholas, I just watched Jake Bartlett’s DUIK intro tutorial and when he rigged his character I wondered if it might be easier for users if the structures were also named left and right (i.e. hands and feet) instead of having numbers or is this for coding purposes?

Like Jake does it manually with “L” for left and “R” for right to keep it short.

### Tool
- Duik

Thanks, René

**Comment by Nico-Duduf** [comment]
Yes, good Idea, will do ASAP ;)
Thanks
