### ISSUE TITLE
Help panel won't read translation file.

### ISSUE THREAD

**Issue by eZioPan** [RxLaboratory/DuAEF_Duik#288]
Help Panel won't read any translation file, both on Windows and MacOS

**Comment by Nico-Duduf** [comment]
Yes, the help panel translation is not implemented yet, as I did not have time to translate the whole help to Spanish and French (the two translations we did here)

We're going to implement this in a 16.1 version in a few months...

**Comment by eZioPan** [comment]
I will start to translate help into Chinese soon. What filename and file path should I use?
