### ISSUE TITLE
Path Constraint Enhancement Suggestions

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/DuAEF_Duik#360]
# Environement
### Tool & Version
- Duik 16.1.0-Alpha-4

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
- Feature Request

### Expected behaviour
Dear Nicolas, after playing with the Auto-Parent I also did some testing with the Path-Constraint. It is logical that the user has to select the path property of a shape layer or a mask but maybe it would be more intuitive if the user only would have to select the shape layer or layer with the mask – if that is possible to overcome with programming.

Also it might be beneficial to set it up like the Connector in steps. 1) Pick the path 2) Pick the Layer. No more “Create” button as the picking of the layer should already trigger the creation. 

It would also be great to have a visual feedback that a path/layer has been effectively selected. Maybe this could work with a line right under the button (please see attached UI mock-up)? Otherwise it would state something like “No path / Layer selected”.

Does this make sense? Thanks, René

![path_constraint](https://user-images.githubusercontent.com/38455050/48677577-3d7c6c00-eb77-11e8-8da3-da3c24d38e43.jpg)

**Comment by Nico-Duduf** [comment]
UI Improved

Still have to build a way to be able to select a layer and automatically pick the first path found on it

**Comment by reneandritsch** [comment]
Thanks a lot!
