### ISSUE TITLE
ajout de controleurs séparés et autres pitits détails

### ISSUE THREAD

**Issue by kanadiou** [RxLaboratory/DuAEF_Duik#443]
Yo !

quelques idées 
- pouvoir ajouter (en option) les controleurs duik sur un controleur séparé, mais en choisissant celui ci (si plusieurs controleurs) en selectionnant le calque. (comme le copie/colle d'anim par exemple ?) 
image : https://puu.sh/D54bV/1879aa964f.png

Eventuellement proposer de renommer dans ce cas, même si on peut le faire ensuite, à la création ça peut etre plus simple si on a beaucoup de controleurs.

Sur un layer simple, voir s'il faut ajouter une option "thislayer" plutot que le nom du calque, mais ça risque de poser plus de probleme si on le met par defaut, donc préférer l'option actuelle avec le nom de calque.

### Tool & Version
- Duik bassel
### After Effects
- CC2019
- English

### OS
- Windows 10

# What's the issue?
- Feature Request

**Comment by Nico-Duduf** [comment]
note pour comprendre plus tard : suit l'idée de rassembler les effets comme le wiggle et autres automations sur le meme calque controleur dans la comp (en option)
