### ISSUE TITLE
Animation Blender "Loop" option ignores trigger marker duration

### ISSUE THREAD

**Issue by mblais** [RxLaboratory/DuAEF_Duik#518]
**Describe the bug**
With "Loop" option enabled, Blender animations loop forever, ignoring the duration of their trigger marker.

**To Reproduce**
1. Create a Blender animation.
2. Enable "Loop".
3. Observe that the animation continues looping beyond the end of the trigger marker.

**Expected behavior**
Animation loops only until the end of the trigger marker's duration, then stops.

**System (please complete the following information):**
 - OS: Windows 10 x64
 - Version of After Effects: 16.1.1 (Build 4)
 - Version of Duik: 16.1.0

**Comment by mblais** [comment]
Perhaps I misunderstood how this is supposed to work... if so, please remove or reclassify this issue.

**Comment by Nico-Duduf** [comment]
That's more a feature request than a bug; for now you can already stop a loop by animating the loop checkbox ;)

I'll implement this ASAP ;)
