### ISSUE TITLE
Adding a trigger button For animated sequences

### ISSUE THREAD

**Issue by Seabat7** [RxLaboratory/DuAEF_Duik#531]
**Is your feature request related to a problem? Please describe.**
I'm looking for a way to trigger an animation, a blink cycle and key frame the button

**Describe the solution you'd like**
On a parent comp you could trigger a value- slider, etc to plan an animation at keyframeable moments on the timeline

**Describe alternatives you've considered**
With a slider you could turn the blink comp on, but it won't automatically play the sequence- so I'm lost
**Additional context**
HONESTLY, this is the most incredible and powerful tool I've ever seen!

**Comment by Nico-Duduf** [comment]
If I understand correctly, I think this can be done with the [Animation Blender](https://duik-docs.rainboxlab.org/animation-blender-setup.html) which triggers animations with markers, am I right?

**Comment by Nico-Duduf** [comment]
(I still have to record a quicktip to explain it better than the doc though)

**Comment by Seabat7** [comment]
Hi Nicolas,

I followed the instructions and it still will not trigger the blink- What do I have set up wrong? Here is a screen shot of how I’ve set it up. The only thing I can think of is that I need to PRE-COMPOSE the blink and make THAT the animated track


Sam L Siragusa
Producer
MERCY MANOR
ZOODIBLES
seabat7@mac.com

**Comment by Nico-Duduf** [comment]
I don't see your screenshot.
Are you talking about a frame sequence/layer sequence for your animation ?
In this case there's no property to rig with the animation blender, and you'll have to precompose and use the time remap, which can have keyframes and expressions, with the animation blender

**Comment by Seabat7** [comment]
Yes, it is a sequence of png files to simulate the blink. I’ll have to try the time remapping and see how that works for it.

Sam L Siragusa
Producer
MERCY MANOR
ZOODIBLES
seabat7@mac.com
