### ISSUE TITLE
To translate the tools of Duik and User Guide to Portuguese (Brazil).

### ISSUE THREAD

**Issue by wasilveira95** [RxLaboratory/DuAEF_Duik#567]
**Is your feature request related to a problem? Please describe.**
It's not a real problem. But it's a suggestion that will be help a lot of motion designers that doesn't speak English. So, my suggestion is to translate the Duik's tools to Portuguese (Brazil).

**Describe the solution you'd like**
I can help you about it. I can translate the Duik's tools and the User Guide.

**Additional context**
If you agree, I will start it next month.

Thank you very much!! I believe in you all!!

**Comment by Nico-Duduf** [comment]
Thanks so much for this proposition. There have been a portuguese version of Duik for a previous version but it had never been updated.

I'll check to give you the translations from this version if it can help you, and I'll explain the process and the tools we have to "quickly" translate Duik, in the next days.
Are you on Mac or Windows?

For the documentation, it is a good idea, but it's a lot of work, and there's always the difficulty of keeping it up-to-date. That's why I stopped making it both in French and English. But if you're willing to try, we'll see how to best organize this.
Let's start with Duik itself first!

**Comment by wasilveira95** [comment]
I'm using Windows right now.
You can send me the previous version of Duik in Portuguese (if you had), because it will help me too.
So, let's start with Duik first!!

Thanks so much for this opportunity to help all of us.
Good job!

I'm waiting.

**Comment by Nico-Duduf** [comment]
So, everything is read for you to translate Duik in Portuguese. Unfortunately, I'm not able to retrive the portuguese version of older versions of Duik, but I'll check again ASAP.

**Here's how to translate:**

1. Download and unzip DuTranslator
[DuTranslator_WIN_2019-11.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/3827601/DuTranslator_WIN_2019-11.zip)

2. You can launch this translation tool by just double clicking on Dutranslator.exe

3. Open the portuguese translation file
you can get it there: https://github.com/Rainbox-dev/DuAEF_Duik/raw/master/src/duik_required/translation/Duik%20Bassel_pt.json
(Just save the page)

4. And just translate!
If you need any help, feel free to ask me.

**To test your translation in Duik:**
1. Copy the translation file to your `Documents/Duik Bassel.2` folder (something like this: `C:\Users\Duduf\Documents\Duik Bassel.2`)
It has to be named `Duik Bassel_pt.json`

2. Restart Duik, Portuguese should now be available in the list of languages in the settings.

3. Now it's available, select it. To see your changes, just restart Duik.

**Comment by Nico-Duduf** [comment]
Note: if there are differences between Brazilian portuguese and portuguese from Portugal, feel free to do as you prefer ;)

**Comment by Nico-Duduf** [comment]
And finally, just tell me here when you're done, and send me back the file. I'll include it in the next update of Duik!

**Comment by wasilveira95** [comment]
Thank you very much!!
I will translate it in about 2 weeks! That's ok for you or do you think it's long time to do it?

**Comment by Nico-Duduf** [comment]
That's perfect, don't worry, there's no rush ;)

I'll release a small update of Duik when it's ready just to include this translation
