### ISSUE TITLE
offset copy keyframes

### ISSUE THREAD

**Issue by cermmid** [RxLaboratory/DuAEF_Duik#626]
**Is your feature request related to a problem? Please describe.**
I'm doing motion graphics and usually my workflow is that elements appear on screen one after another and then they all disappear simultaneously on last second. So i keyframe all the properties one second before the end and than i want to copy every first frame of all elements to the same point in time, but they're offseted, so i have to slide them manualy.

**Describe the solution you'd like**
I think a good idea would be to just put a check box next to "copy", "paste" anim with label "offset" wich should be turned on by default, so the copy/paste would work like it's working now. but if somebody (for example me :D) would turn it off it would paste all the keyframes in the same point in time.. and that would be awesome.

**Describe alternatives you've considered**
I don't know i think that's the simplest solution.

**Additional context**

**Comment by Nico-Duduf** [comment]
Good suggestion, I'll add this in the options of the copy/paste tool. Thanks

**Comment by Nico-Duduf** [comment]
In the new Duik Ángela, 17, there's a button to align keyframes. I think that should be what you need
