### ISSUE TITLE
i loved the note in after effects.

### ISSUE THREAD

**Issue by Dheerajvis** [RxLaboratory/DuAEF_Duik#630]
**Is your feature request related to a problem? Please describe.**
There is no problems in notes. that is very useful tool

**Describe the solution you'd like**
I would like too request you that if we can save the notes as a text file for particular projects and open the text file in notes for particular project.

**Describe alternatives you've considered**
I would like to give an example. assume that i'm working on a project named A and i have noted down some important stuff for project A in between i'm working on another project name B i have noted some important notes. if there will be an feature that can save that particular texts as a text file and can open that text file in notes tool that will be very helpful.

**Additional context**
thank you so much for this beautiful feature.

**Comment by Nico-Duduf** [comment]
This is an interesting feature. I think it could even be nice to have per-comp notes, I'll see how both could be implemented.

Thanks

**Comment by Nico-Duduf** [comment]
done in Duik 17
