### ISSUE TITLE
Bug, crash, Rig IK

### ISSUE THREAD

**Issue by MrPolo67** [RxLaboratory/DuAEF_Duik#677]
**Describe the bug**
crash Duik, open Extendtoolscript

**To Reproduce**
1. I make a simple IK
2. select Layers and controller
3. click on IK 'create'

**Error description, if any**
File:  bassel 2.jsx
Line number: 14563 (the same as usual :)
Error message:  none

**Expected behavior**
Just want to make a simple rik IK (arm, forearm, hand)

**Screenshots**
![Bug_2020_05_08_Rig-IK_Create](https://user-images.githubusercontent.com/65020969/81408036-c2c55900-913c-11ea-894a-c4ab101b1a66.jpg)

**System (please complete the following information):**
 - OS:  win 10
 - Version of After Effects: cc2019, v16.1.2
 - Version of Duik: bassel 2 v16.2.1

**Additional context**

**Comment by Nico-Duduf** [comment]
Can you try the fix/uninstall procedure from the user guide and tell me if you still have the issue?

https://duik-docs.rainboxlab.org/install-duik.html#fix-uninstall-duik

**Comment by Nico-Duduf** [comment]
Also, I think disabling javascript debugging might fix the issue
