### ISSUE TITLE
Error creating 'Auto-rig and IK' controllers - process is stalling before complete

### ISSUE THREAD

**Issue by jamiesteedman** [RxLaboratory/DuAEF_Duik#699]
After going through all the steps to create the character rig and animate it with Duik Bassel, when I click the button 'Auto-rig & IK', it starts to create the controllers, but it gets stuck on the 'MAGIC IS HAPPENING' comp and goes no further. The controller creation is incomplete and so this leads me to believe there is a bug somewhere. Does anyone know if I am correct and/or if they know what is wrong?

**To Reproduce**
1. Create or import a character with layers into After Effects
2. Create all the required structures for the character
3. Select the structures and click 'Auto-rig & IK' This is where I am getting the error

There is no error message, just simple a stall in the process (i.e. the comp that opens saying 'MAGIC IS HAPPENING' nothing further happens. 

**Expected behavior**
The expected bahviour I have is that it should automatically return to the comp with the character and have all the completed control layers for the character rig.

<img width="1730" alt="Screenshot 2020-06-28 at 19 22 48" src="https://user-images.githubusercontent.com/67556621/85955171-caeb8900-b974-11ea-8e3c-8932abf0fef3.png">

**System (please complete the following information):**
 - OS: Catalina Version 10.15
 - Version of After Effects: 2020
 - Version of Duik: v16.2.14

I'm pretty new to DUIK and GitHub so apologies if I'm not too clear on things!

**Comment by Nico-Duduf** [comment]
Hi,

I'll need to  see what Structures you've created/selected to run the autorig, to know what's going on.
Also, can you switch to the Dev & Debug mode in the settings and post a screenshot of the error which may be shown? Thanks
