### ISSUE TITLE
can't find orientation constraint in duik 3

### ISSUE THREAD

**Issue by GabbyToon** [RxLaboratory/DuAEF_Duik#737]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Version of After Effects: 
 - Version of Duik: 

**Additional context**

**Comment by Nico-Duduf** [comment]
Duik 3 ??

Have you checked which UI mode you're in?
https://duik-docs.rainboxlab.org/first-look-at-duik.html#rookie-standard-expert-or-god-mode

**Comment by GabbyToon** [comment]
sorry, 3(THREE) was a typo
I cant see how can I see any settings, everything looks so different from your tutorials, just waste of time by searching, stressed out. it's almost morning here, I was trying my best all night.... also its really hard for me to understand your accent, I am not a native English speaker, and this tutorial is a huge challenge for me...
Can I please have my return of the tutorial i bought today?I don't think I can make it... sorry. I can't do this... may be next time.. I don't want to start to hate DUIK as I am about to right now....Thanks for understanding, here are screenshots about the purchase

Sincerely, 
      Gabriella 

 
 

    On Monday, September 28, 2020, 06:42:19 AM EDT, Nicolas Dufresne <notifications@github.com> wrote:  
 
 


Duik 3 ??

Have you checked which UI mode you're in?
https://duik-docs.rainboxlab.org/first-look-at-duik.html#rookie-standard-expert-or-god-mode

**Comment by Nico-Duduf** [comment]
Hi,

I did not get the screenshots, as your posting on Github which does not transfers attached files (you have to come post them on the website).

I don't understand why Duik should be so different from the tutorial, as the version used in the official tutorial is - almost - the latest one.
Can you tell me exactly what tutorial you've bought? Just post the link so I can see.

I'm sorry for the inconvenience, we're going to fix this.

Thanks.
