### ISSUE TITLE
Parenting Across Comps

### ISSUE THREAD

**Issue by woozygoozy** [RxLaboratory/DuAEF_Duik#741]
Parenting across comps is not working - when I try to select the comp in the duik menu, the menu is always empty...

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
I should get a list of all the comps in the project that I can select...

**Screenshots**
<img width="400" alt="Screen Shot 2020-09-29 at 20 43 44" src="https://user-images.githubusercontent.com/44062706/94630799-c052cf80-0294-11eb-8219-1266d390e6ab.png">

**System (please complete the following information):**
 - OS: OSX 
 - Version of After Effects: 17.0.6 / 17.1.4
 - Version of Duik:  16.2.18 / 17

**Additional context**

**Comment by Nico-Duduf** [comment]
Well, actually it should not list all comps, but just those which have a direct relationship (parent comps or precomps).

https://duik-docs.rainboxlab.org/parent-accross-compositions.html

Can you check that?
