### ISSUE TITLE
DUIK stucked on languages choice screen or unable to execute script at line 314. p is undefined

### ISSUE THREAD

**Issue by Nico-Duduf** [RxLaboratory/DuAEF_Duik#776]
https://forum.rainboxlab.org/viewtopic.php?f=11&t=1089

happens on all Ae 17.x versions, seems to be on both Win & Mac

duik_settings file is missing,
if ae is started in another language than english it works
if settings file is created manually, this error: `unable to execute script at line 314. p is undefined`

It seems that this is not linked to Duik but an issue with Ae, when it is installed in English on a non-English OS

**Comment by futurGH** [comment]
Same issue here, albeit my OS and After Effects are both in English. And it doesn't matter which language I try, stuck at the same point.

After Effects 2020, Windows 10.

**Comment by AhmedSebaie** [comment]
any solutions after changeing the windows version same problem happens

**Comment by AhmedSebaie** [comment]
any solutions after changeing the windows version same problem happens

**Comment by Nico-Duduf** [comment]
If other people have this issue, please give more info:

Always state the exact version of Duik, of After Effects (as seen in the help/about box) and of the Operating System, thanks

**Comment by AhmedSebaie** [comment]
Hello is there any solution for the problem 
I reinstall my Windows Again and the Duik work for like 3 Days then I got this unable to execute script at line 314. p is undefined

I tried to solve the problem by uninstalling Duik and re install it I got this :D 
DUIK stucked on languages choice screen  
 is there is any hope to keep working with Duik  I couldn't fix this until now  and I think the best way to re install it is to reset the windows    so I think there is a file should be deleted in the system to let it work again please give me a solution

**Comment by msongz** [comment]
try delete the files on /Document which generated by DUIK

**Comment by AhmedSebaie** [comment]
> try delete the files on /Document which generated by DUIK

[<a href="https://files.fm/u/k7t6q63es#/view/Untitled.png"><img src="https://files.fm/thumb_show.php?i=22bssp3y6"></a>](url)
as you see nothing new i deleted the folder that is in document folder

**Comment by AhmedSebaie** [comment]
> If other people have this issue, please give more info:
> 
> Always state the exact version of Duik, of After Effects (as seen in the help/about box) and of the Operating System, thanks

I have the latest ver of duik and wind 10 and  aftereffect 2020 ver 17.1.1 build 34

**Comment by Nico-Duduf** [comment]
This seems to confirm it's an issue specific to After Effects 17.x (2020). Can you try with 2021 or 2022?

**Comment by AhmedSebaie** [comment]
> This seems to confirm it's an issue specific to After Effects 17.x (2020). Can you try with 2021 or 2022?

[https://ibb.co/ysyFsJq](url)
[https://ibb.co/t4LZVyp](url)

I have installed after effect 2021  and  still have same problem

**Comment by AhmedSebaie** [comment]
Any Solutions please 🍡

**Comment by AhmedSebaie** [comment]
it stoped working agian :D

**Comment by Nico-Duduf** [comment]
I can't find what's wrong.
Can you post a list of other scripts and extensions installed/you're using? Expecially any you have installed just before it broke again.
There may be an issue in another script/some conflict, let's try to diagnose that

**Comment by UZKADQ** [comment]
i have a similar problem.
the following error appears:

"unable to run script on line 35706. null is not an object"

i use windows 10 pro
after effects 18.4.1
duik bassel 2___16.2.30
![Captura de tela 2022-02-03 130118](https://user-images.githubusercontent.com/98966283/152380603-5600ea5a-575c-43dd-927e-0770c8c38136.png)



the error appears when starting after effects!

I've already tried:
1_uninstall the script along with all its folders and install it again.
2_updated AE to version 22.0.1
3_tried to install an old version of duik
4_uninstalled all adobe software, including deleting registries and all plugins and other scripts and installing again.

nothing worked :/
