### ISSUE TITLE
After reopening project and applying Auto-Rig Duik creates red rounded triangles

### ISSUE THREAD

**Issue by Eli-Loc** [RxLaboratory/DuAEF_Duik#796]
**Describe the bug**
After reopening project and creating new IK rigs Duik doesn't create them properly. Instead it creates red rounded triangles as shown on screeshots. Connectors don't work too.

**To Reproduce**
1. In new project create structure i.e. Hand or Leg
2. Apply to this structure Auto-rig
3. Save project
4. Restart the computer
5. Open Saved project
6. Create another structure
7. Apply to newly created structure Auto-rig

**Error description, if any**
No error
File: 
Line number:
Error message: None

**Expected behavior**
Creating Auto-rigged structure is expected

**Screenshots**
![Duik broken rig](https://user-images.githubusercontent.com/35794139/104040445-537a9a00-51e0-11eb-929c-366e162f4425.gif)

**System (please complete the following information):**
 - OS: Windows 10, 64-bit
 - Version of After Effects: 17.5.0
 - Version of Duik: 16.2.2.4

**Additional context**
Normal behaviour if create another project.

**Comment by Nico-Duduf** [comment]
That's very strange and I can't reproduce here.
Can you send me an aep where this happens so I can see what's in it and run some other tests with it?

**Comment by Eli-Loc** [comment]
Tested in AE version 17.1 everything seems to work fine
Here is the file
[Duik Rig IK Broken.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/5862630/Duik.Rig.IK.Broken.zip)
