### ISSUE TITLE
Auto Rig Torso Proposal/Suggestion

### ISSUE THREAD

**Issue by Morganimator** [RxLaboratory/DuAEF_Duik#804]
**Is your feature request related to a problem? Please describe.**
No, not a problem per se, I just think the torso/head component of the auto rig system could be improved.

**Describe the solution you'd like**
Please have a look at the video at this link and the attached project file to see my suggested solution:
https://drive.google.com/file/d/1l06Det20AEJ9mRufs6WPB6lv_jrJTkOP/view?usp=sharing
[AutoRigTorsoProposal_v01_folder.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/5899544/AutoRigTorsoProposal_v01_folder.zip)

**Describe alternatives you've considered**
It's all in the video and project file.

**Additional context**

**Comment by Nico-Duduf** [comment]
Finally, it's done!
It uses a new "Bézier FK", which allows exactly what you're doing with your spine, and adds a few other ways to manipulate the spine. No matter what, the torso is its own single layer, controlled by a simple rotation, as it should be like in all usual rigs ;)
Will be available very soon in the new Duik Ángela Alpha

**Comment by Morganimator** [comment]
Yay! Thanks so much for taking my suggestion. Very excited for Duik Angela!
