### ISSUE TITLE
Auto flop and some useful features

### ISSUE THREAD

**Issue by chihuahuashka** [RxLaboratory/DuAEF_Duik#808]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem, I just saw this video and thought it would be nice to see similar improvements. Especially "auto flop"

**Describe the solution you'd like**
all the things I think would be useful - see in this video
https://www.youtube.com/watch?v=038sZ7eV5Io&feature=youtu.be&ab_channel=LuisMart%C3%ADnez

**Describe alternatives you've considered**

**Additional context**

**Comment by Nico-Duduf** [comment]
done in Duik 17
