### ISSUE TITLE
All keyframe values change even if want to change value of one.

### ISSUE THREAD

**Issue by Quocca1029** [RxLaboratory/DuAEF_Duik#811]
**Describe the bug**
At animation tab :
1. Even if I want to change keyframe value of just one keyframe, all keyframe(any kind of) values are changed. 
2. I use ctrl + s save method, but duik animation value changes are not saved. After Effect changes are saved. Is there any other way to save duik values..? 

**To Reproduce**
1. set keyframes.
2. select one keyframe and set duik animation keyframe value.
3. check other keyframe value.

**Error description, if any**
File: -
Line number: -
Error message: -

**Expected behavior**
The change of the keyframe what I selected.

**Screenshots**
-

**System (please complete the following information):**
 - OS: MacOS BigSur
 - Version of After Effects: 2020
 - Version of Duik: Bassel2 v.16.2.28

**Additional context**
-

**Comment by Nico-Duduf** [comment]
I can't reproduce the issue here, even when on MacOS

Could you make a screen recording so I can have a look in details at what's going on your side?
