### ISSUE TITLE
Animation blender don't work

### ISSUE THREAD

**Issue by eunts** [RxLaboratory/DuAEF_Duik#824]
Don't create new layer after press button Blend.

**To Reproduce**
1. Create shape layer.
2. Position animation.
3. Press button Set
4. Resize time ruler.
5. Press button Blend

**Comment by Nico-Duduf** [comment]
Here the Blender works correctly

From your step by step description, it seems you did not set the "Composition to set up" and the "Control from" comps. You absolutely need to set these to set the blender up.

Can you confirm if it is working or not when correctly set up?
Thanks for your feedback
