### ISSUE TITLE
2D camera tilt

### ISSUE THREAD

**Issue by Daminous** [RxLaboratory/DuAEF_Duik#829]
Duik 16.2.28

Si la première clé d'animation du tilt est à 0° dans la timeline, les valeurs des autres keyframes sont ok.
Si la première clé d'animation du tilt n'est pas à 0 dans la timeline, les valeurs deviennent étranges.
Par exemple : si on anime le tilt d'une valeur de -10° (keyframe 1) à 0° (keyframe 2), la seconde keyframe est égale à +10.

Si on désactive l'expression sur le tilt, le résultat est correct.
Si on supprime le "+ valueAtTime(0)" à la fin de l'expression, le résultat est correct.

**Comment by Nico-Duduf** [comment]
fixed (in duik 17)
