### ISSUE TITLE
Easing presets drop-down not showing correctly

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/DuAEF_Duik#835]
**Describe the bug**
When pressing the Easing drop-down in the animation tab in DUIK 16.2.29 the list immediately disappears again or is not shown at all.

**Expected behavior**
List should stay on screen.

**Screenshots**
![presets](https://user-images.githubusercontent.com/38455050/121850806-9b50a080-cced-11eb-9c45-dc908fd3864f.gif)

**System (please complete the following information):**
 - OS: 11.3.1
 - Version of After Effects: 17.7.0.45
 - Version of Duik: 16.2.29

**Comment by Nico-Duduf** [comment]
Hi René, sorry to reply late

I have to test this on a mac, I can't reproduce the issue on windows.
You can try disabling all the sanity tests (bottom-right brain icon) and see if it's better, it may be one of them which interferes with the UI

**Comment by reneandritsch** [comment]
Dear Nicolas, I will try that. Thanks, René
