### ISSUE TITLE
Spring automations doesn't work ( kleaner in the place)

### ISSUE THREAD

**Issue by BIGbigmarc** [RxLaboratory/DuAEF_Duik#836]
**Describe the bug**
While I would have a spring automation on key animation, I have always the kleaner automation. On any type of layer, on any transformation

**To Reproduce**
1. I select One key of any transform. ex : position, scale, opacity, ...
2. i clic on the automation button Spring
3.  and I have the kleaner

**Error description, if any**
no error message appear

**Expected behavior**
I expected to have the srping expression and 2 value to change on my effect controle ( like before - simple to [use)](url)

**Screenshots**

**System (please complete the following information):**
 - OS: windows 10 famille 2004 19041.1052
 - Version of After Effects: 18.2.1 ( build 8 )
 - Version of Duik: v16.2.29

https://user-images.githubusercontent.com/86347203/123067375-3abe1380-d411-11eb-8040-62d6fe51453d.mp4

Does Spring dead ? and replace by Kleaner ? I love the spring for his minimal input ( just 2 ) .

Thnaks.. and thanks for all your work !

**Comment by Nico-Duduf** [comment]
Yes sorry, the spring has been replaced by the kleaner, which does exactly the same thing (if you use it only for the spring, there's still the same two parameters in the "follow through" section of the kleaner
