### ISSUE TITLE
Animation Blender - List broke when delete all markers

### ISSUE THREAD

**Issue by Kuzobugi** [RxLaboratory/DuAEF_Duik#838]
**Describe the bug**
Je créé les liens animation blender, tout se passe bien, je met des marqueurs sur le nouveau calque Animation Blender via l'outil dans le panneau Animation de duik. Ca me trouve toutes les animations dans la liste, mais si je supprime tous les marqueurs pour recommencer à zéro, la liste n'affiche plus rien.

**To Reproduce**
Voir cette vidéo : 
https://user-images.githubusercontent.com/42748374/123989764-7d5f8d00-d9c9-11eb-8123-9bcd2ae02d3f.mp4
Avec le petit cadeau en bas à droite de l'espace de travail :)

**Error description, if any**
File: 
Line number:
Error message: Pas de messages d'erreurs

**Expected behavior**
Qu'il y ait toujours la liste

**Screenshots**
https://user-images.githubusercontent.com/42748374/123989764-7d5f8d00-d9c9-11eb-8123-9bcd2ae02d3f.mp4

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 18.2.1
 - Version of Duik: 16.2.29

**Additional context**
Bon après c'est pas urgent j'ai réussi à trouver le truc, faut juste faire gaffe.

**Comment by Nico-Duduf** [comment]
Merci c'est bien noté !
On freeze le dev de Duik Bassel -> tout sur Duik 17 sansNom, donc le fix sera dans la beta de Duik 17 vers septembre ;)
