### ISSUE TITLE
Character Rig breaking in After Effects

### ISSUE THREAD

**Issue by Kash-Design** [RxLaboratory/DuAEF_Duik#839]
**Describe the bug**

**To Reproduce**
1. I have a project file from School of Motion where there is a character rig, it breaks after I change the workspace
2. if the app crashes the character rig breaks 
3. it also affects the autosaves even though rigs were fine while saving. 

**Error description, if any**
File: -
Line number: -
Error message: none

**Expected behavior**
The rigs should maintain at all times, right now certain parts like hand direction and props on off breaks while the rest stays intact. 

In my screenshot the direction of the front hand should be empty and the direction switched, right now it is with a prop and I cannot turn the direction or turn off the prop in hand. 

**Screenshots**

1. 
![axel_SCENE_B (0-00-08-11)](https://user-images.githubusercontent.com/86772811/124097592-fdcece00-da5b-11eb-83f3-150934ddef94.png)

[

**System (please complete the following information):**
 - OS: 11.4
 - Version of After Effects: 18.2.1
 - Version of Duik: 16.2.29

**Additional context**
Purging media and disc cache in AE didnt work, neither did reinstalling DUIK. If AE crashes the rig breaks, sometimes it does when switching between Workspaces. It also affects Autosaves even though everything was fine while animating.

**Comment by Nico-Duduf** [comment]
Hi, can you send me the project so I can test on my side?

Thanks!

**Comment by Kash-Design** [comment]
> Hi, can you send me the project so I can test on my side?
> 
> Thanks!

Sure, I uploaded the file with no animation in it and one where the rig started breaking on multiple occasions.

[cab_day29_finalproject_v29.zip](https://github.com/RxLaboratory/DuAEF_Duik/files/6824841/cab_day29_finalproject_v29.zip)
[20210413-FinalProject-KashBhatia-7-4.zip](https://github.com/RxLaboratory/DuAEF_Duik/files/6824844/20210413-FinalProject-KashBhatia-7-4.zip)

**Comment by Nico-Duduf** [comment]
Thanks, I'll have a look tomorrow!

**Comment by Kash-Design** [comment]
@Nico-Duduf were you able to look into this? No worries if it takes time.

**Comment by Nico-Duduf** [comment]
Sorry to reply late, I finally had a look at the project.

So: This character was rigged something like 6 years ago with After Effects CC2014 and an oooold version of Duik

The expressions in there are not compatible with the new expression engine from the latest versions of After Effects, you have to go to the project settings and on the expression tab switch the engine to the "legacy" mode

**Comment by Kash-Design** [comment]
No worries and Thank you so much for looking into this!
