### ISSUE TITLE
Error recurrente

### ISSUE THREAD

**Issue by jpgv930921** [RxLaboratory/DuAEF_Duik#840]
**Describe the bug**
el programa no funciona, aparece una clase de error que no permite usar el duik, que es Error de After Effects: fallo de comprobación interna, {unexpected martch name serched in group} (29::0)
**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/87336037/125342872-04422d00-e31b-11eb-9a3d-59b2c0cfefbe.png)
![image](https://user-images.githubusercontent.com/87336037/125343017-32c00800-e31b-11eb-8874-50a9e1ade6d7.png)
las herramienta de Duik se queda en blanco, ya no esta Rojo o verde.
**System (please complete the following information):**
 - OS: 
 - Version of After Effects: 2020
 - Version of Duik: Duik Bassel2

**Additional context**
no es la primera vez que pasa, ya a pasado varias veces con diferentes versiones.

**Comment by Nico-Duduf** [comment]
Can you give me more details about the versions of Ae and Duik ?
The exact version of Duik as shown in the bottom of the panel,
And the exact version of Ae as shown in the about box (help menu > about) ?
Thanks!
