### ISSUE TITLE
AE stops responding after opening DUIK

### ISSUE THREAD

**Issue by Gitasman** [RxLaboratory/DuAEF_Duik#841]
**Describe the bug**
Everything works fine when I try to open duik ui panel on small projects, but when I open it with bigger projects, the cursor starts thinking and the ae window says its not responding.
But keyboard buttons still work, I can start a preview, navigate etc. with keyboard.
It takes like 5-10 minutes before it unfreezes, sometimes it gives an error
"unable to execute script at line 9629"

**To Reproduce**
1. Open after effects project 255mb
2. Press the duik bassel ui panel

**Error description, if any**
unable to execute script at line 962

**Expected behavior**
just open normally as usual without freezing

**System (please complete the following information):**
 - OS: windows
 - Version of After Effects:  2020 and 2019 as well the same problem
 - Version of Duik: 16.2.29 

**Additional context**

**Comment by Nico-Duduf** [comment]
Can you send me the project so I can test? Thanks!

**Comment by Gitasman** [comment]
https://drive.google.com/file/d/1KoC0BU2jaE7Ov1YMqNQ7fCsbL4mDHAKS/view?usp=sharing 

Here u go, sometimes it does work after a couple of minutes of thinking, but a lot of the time.
I click on duik ui panel, and it just freezes.

**Comment by Nico-Duduf** [comment]
I can't open your file, it seems the zip is corrupted.

Anyway, my guess is it's an issue with the automatic sanity checks (which will change in the next version); for now, you can disable them and see if it's better.
Click on the *brain* icon at the bottom right of the panel of Duik, and click on 'globally switch all tests' to disable them all (or choose the ones you wish to deactivate. I think there must be just one which fails, probably linked to the number of items in the project)
