### ISSUE TITLE
Duik Bassel.2 v16.2.30

### ISSUE THREAD

**Issue by ANIMA67** [RxLaboratory/DuAEF_Duik#848]
EL Archivo Duik Bassel.2 v16.2.30 Zip produce un error en la descarga que no se termina de realizar correctamente

1. ingreso a la pagina https://rainboxlab.org/tools/duik/
2. doy click en el archivo zip
3. aparece una barra de descarga
4. no se logra descargar correctamente, porque el archivo zip presenta una falla

esperaba que el archivo se descargara correctamente para WinX64Bits 

Versión After Effects 2021

este error se viene presentando hace varios días, muchos diseñadores no han podido realizar sus proyectos debido a esta falla masiva.

por favor dar solución, Muchas gracias

**Comment by Nico-Duduf** [comment]
Hi, thanks for your report.

Here everything seems to work correctly, and there from what I can see in the logs, many people are still correctly downloading Duik.

What's your country? Sometimes there may be issues from some countries.. If you still can't download Duik an alternative mirror is available on Github, here: https://github.com/RxLaboratory/DuAEF_Duik/releases

Now that I have a look in details on the logs, It seems yesterday there's been an attack on the the server from Pakistan, resulting in many simultaneous downloads, that may explain some issues but I think now it's working correctly. Let me know!

**Comment by ANIMA67** [comment]
Cordial Saludo Nico, Respecto a su respuesta efectivamente me permitió descargar el archivo por medio del link https://github.com/RxLaboratory/DuAEF_Duik/releases 

pero lastimosamente por medio del enlace  https://rainboxlab.org/download-duik-bassel/ aun me presenta fallas al descargar como: 
1. la descarga se demora varias horas
2. no se logra efectuar la descarga durante un tiempo predeterminado

es mas accesible descargar archivos por medio de: https://github.com/RxLaboratory/DuAEF_Duik/releases 
que en la pagina:  https://rainboxlab.org/download-duik-bassel/ 

Por favor dar solución a esta falla
