### ISSUE TITLE
Layer manager : UI - pipette sous la partie outil

### ISSUE THREAD

**Issue by Daminous** [RxLaboratory/DuAEF_Duik#851]
Proposition de rapatrier la pipette sous la partie outil, la placer dans la partie "label".
![unknown](https://user-images.githubusercontent.com/25245310/131481215-14960719-3cb3-4bc9-8f9a-f756169d2d4c.png)

**Comment by Nico-Duduf** [comment]
Note spéciale pour ce magnifique orange nostalgie 😄

**Comment by Nico-Duduf** [comment]
![image](https://user-images.githubusercontent.com/8526542/135646091-ac2c6c31-34a3-4d4d-af5f-a790671bb033.png)
Here's how it will be finally
