### ISSUE TITLE
DUIK 17 Alpha UI suggestions

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/DuAEF_Duik#852]
Dear Nicolas!

After the complete overhaul of the UI it takes a little to get used to the new look. Definitely takes up less space. I like the categories and then the subcategories for the limbs.

To make it more obvious once the user is in the limb options, maybe add the word »create« at the bottom. This made it 100% clear in Bassel what happens when you click at the bottom. Now it just says “Arm” which only looks like information not like a request.

![arm](https://user-images.githubusercontent.com/38455050/131581793-bedb6e38-3a0f-4101-9f04-4e9426339692.png)

When looking at the spacing between icons in Bassel and 17, Bassel feels more accessible due to the bit of more space. Maybe there is a possibility for more room between the icons in 17 as well – makes it easier on the eyes.

![comparison](https://user-images.githubusercontent.com/38455050/131582126-a2c6e357-36af-4bc0-80cf-0b7cd484bcf1.png)

The top line of command icons like »select«, »show« etc. could also be spaced out a little more. Especially on the controller section I think usability suffers because they are so close to the tabs and the controller icons in a vertical space as well.

**Comment by Nico-Duduf** [comment]
Thanks for the feedback, there are a lot of little tweaks like that I'll have to make before the final release!

I've tried soemthing else in the controllers panel in the second alpha, but I'm not sure it's better ^^

**Comment by Nico-Duduf** [comment]
all done!
