### ISSUE TITLE
Add edit mode in the parent constraints or as a tool of the constraints tab

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/DuAEF_Duik#854]
Dear Nicholas!

I just got an e-mail in my inbox, in which a user describes a workflow problem and I thought this could be something that might be possible for a genius like you. It has to do with temporarily unparenting a layer so it can be moved independently and then activate all the children again. Not with the auto parent function. But in this way:

The user selects a parent and pushes a button in the UI in wich all children are released but »remembered« by DUIK. The the parent can be moved independently. After changing the position the button is pushed again and all children are parented again to that parent.

Maybe the Auto Parent in combination with the SHIFT key could be used for this.

Would that be possible?

**Comment by Nico-Duduf** [comment]
That's already in duik ;)
In the tools tab, it's the "edit mode" http://duik.rxlab.guide/rigging-tools.html#toggle-edit-mode

I like your suggestion to add it on the autoparent button though, I'll do that in Duik 17! Probably on Alt Click

**Comment by Nico-Duduf** [comment]
Or maybe even add it there as a real tool and not hidden behind the auto-parent, to help discoverability. The UI of 17 has enough room ;)

**Comment by Nico-Duduf** [comment]
Or one of the (too) small tool buttons... something like that!

**Comment by reneandritsch** [comment]
Ahhh – I tried the toggle edit mode in the »Structures Tab« but that is already reserved for rigged bones. I totally forgot about »Toggle Edit« mode in the tools section – thank you!
