### ISSUE TITLE
Expression Error with Autorig on a Bird Spine (Legacy Extendscript)

### ISSUE THREAD

**Issue by Hero-Studio** [RxLaboratory/DuAEF_Duik#856]
When doing the autorigging on a bird spine using Legacy Extendscript.

1. Create a bird spine 
2.  Autorig
3. You get the error on "C | Character | Spine_Root"

**Error description, if any**
File:  
Line 22
Error message: 
Error at line 22 in property "Rotation" of layer 6('C | Character | Spine_Root') in comp 'YOUR COMP'.

![image](https://user-images.githubusercontent.com/68726902/132099518-a9bad02d-1d1a-4a3b-8962-0d312a128d95.png)

**System (please complete the following information):**
 - OS: windows 10
 - Version of After Effects: 18.4.1
 - Version of Duik: 17.0.0-Alpha02

**Comment by Nico-Duduf** [comment]
fixed!
