### ISSUE TITLE
Create Controllers 

### ISSUE THREAD

**Issue by exdmo** [RxLaboratory/DuAEF_Duik#857]
Les icones "Controllers" ne s'affichent plus. 
 
1. Clique "Rigging"
2. Clique "Create Controllers

File: 
Line number: 3798
Error message: Unable to execute script at line 3798. Expected: ] - Execution halted

![Duik-1](https://user-images.githubusercontent.com/90309403/132475447-e3b24a49-7462-4046-b80e-2b047f4b05f9.png)
![Duik-2](https://user-images.githubusercontent.com/90309403/132475457-e7aa6471-46a7-4074-a801-714453113de9.png)

**System 
 - OS: Win 10
 - Version of After Effects: 18.4.1
 - Version of Duik: 16.2.30

J'ai essayé de passer par la fenêtre "Duik Controllers" directement mais impossible aussi.
Error message : Unable To execute script at line 12940. is out of range

**Comment by Nico-Duduf** [comment]
Hello,

Bizarre... Est ce que tu as le "déboggage javascript" actif dans les préférences/scripting de After Effects ? Si oui je t'invite à le décocher et voir si ça va mieux.
Si non, After fait ch... et ya un nouveau bug à contourner, je jetterai un oeil à ça
