### ISSUE TITLE
Importing smal comp in bigger comp

### ISSUE THREAD

**Issue by PoppyPop38** [RxLaboratory/DuAEF_Duik#862]
**Describe the bug**
DuIk v16.2.30
Rig a character in comp 01 some layers have bones created with puppet tool, some not
Importing comp 01 in comp 02  much bigger,,extract the controlers, and if i rasterize the imported comp the  layers with puppet tol loose the rig

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
restoring the ik

**Screenshots**

![02](https://user-images.githubusercontent.com/90910944/133788290-4ca01bb1-79b1-4b34-a4ef-72ae79105849.jpg)
![01](https://user-images.githubusercontent.com/90910944/133788294-c89fbcb8-b647-4e08-b7ae-37cae548ee32.jpg)
![03](https://user-images.githubusercontent.com/90910944/133788301-dfab1d6a-c581-401d-a9fd-51089c5d1d39.jpg)

**System (please complete the following information):**

 - OS:  windows 10 pro
 - Version of After Effects:   18.4.0 
 - Version of Duik:  v16.2.30

**Additional context**

**Comment by Nico-Duduf** [comment]
Est ce que tu peux m'envoyer le projet que j'y jette un oeil ? ça sera plus simple ! merci

**Comment by PoppyPop38** [comment]
Merci de répondre mais je l'ai écrasé  ! J'ai recommencé mon rig de perso sur une compo plus grande afin d'eviter les soucis (c'est bien les membres en" bone de puppet" qui n’acceptaient pas la rasterization,peut être dut au fait d'avoir déplacer de beaucoup les icones des contoleurs dans ma precomp.
Enfin maintenant ça roule.
Encore merci de l’intérêt que tu porte au utilisateur et bravo pour ces super outils.Je ne manquerais pas de passer par la case patreon...
Marc
 

De : "Nicolas Dufresne"
A : "RxLaboratory/DuAEF_Duik" ,"PoppyPop38" ,"Author"
Envoyé: vendredi 17 Septembre 2021 15:47
Objet : Re: [RxLaboratory/DuAEF_Duik] Importing smal comp in bigger comp (#862)
 

 

Est ce que tu peux m'envoyer le projet que j'y jette un oeil ? ça sera plus simple ! merci

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
