### ISSUE TITLE
Duik bassel fige After Effect

### ISSUE THREAD

**Issue by Camaieu54** [RxLaboratory/DuAEF_Duik#863]
**Describe the bug**
Bonjour, j'ai un problème récurant qui s'amplifie avec la nouvelle version d'After Effect CC 2021. Au survole du panneau Duik, After se fige et plante comme si Duik cherchait une connection internet extérieur qui n'arrive jamais. J'adore ce plugin dont je me sert depuis plusieurs années, mais là, je bloque et pourtant, je me voie mal me passer de lui.

**To Reproduce**
1. au survole du panneau Duik
2. After Effect cherche dans le vide
3. After Effect plante

**Error description, if any**
File: 
Line number:
Error message: pas de message d'erreur

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: windows 10
 - Version of After Effects: CC 2021
 - Version of Duik: Duik Bassel 2_16.2.30

**Additional context**
Ce problème existait dans les versions précédentes, mais n'allait pas jusqu'à planter After Effect. Au bout de quelques seconde, tout redevenais normal.
Merci de votre aide future, je dois avouer que je suis vraiment dans la M...

**Comment by Nico-Duduf** [comment]
Bonjour,

Essaie de réinitialiser les préférences de Duik, en supprimant le dossier "Duik Bassel.2" dans ton dossier "mes documents"
Ensuite je pense que le souci vient des "sanity checks" ; depuis un projet vide (qui devrait éviter à duik de planter), clique sur l'icone "cerveau" tout en bas à droite pour afficher les sanity checks en question, et désactive les vérifications automatiques ; l'un de tests doit planter sur certains de tes projets. Ces soucis seront corrigés dans les procchaines versions.

**Comment by Camaieu54** [comment]
Merci Nicolas, c'était bien ça. Problème résolu. J'en profite pour te remercier toi et ton équipe pour le développement de ce fabuleux plugin que je suis depuis son apparition. Je ne pourrais plus m'en passer. Je le transmet à mes élèves et les formes à son utilisation lors de mes cours de motion design. Merci d'exister et bonne continuation.
