### ISSUE TITLE
AE crashes when open project or click Auto-rig

### ISSUE THREAD

**Issue by kotydwa76** [RxLaboratory/DuAEF_Duik#865]
I've just had to reinstaled Windows 10 and my Adobe CS6 - I know it's very old but I have a reason to keep it so long. (money)
When I open a project with DUIK I got this info and program crashes.

![Przechwytywanie w trybie pełnoekranowym 29 09 2021 122914 bmp](https://user-images.githubusercontent.com/72746131/135266789-31197583-fbc7-4c3b-8f65-834838d46f3b.jpg)

It also crashes when I try to auto-rig new bones (only without any info)

I tried latest Duik as well some older verstion 16,2.16. There was a place with all previous versions of DUIK but I can't find it now.

It all worked perfectly fine before the reinstalation and now I'm in a deep shit :/

**Comment by Nico-Duduf** [comment]
These alerts are there because the project was rigged with Duik 15.
older versions are there: https://github.com/RxLaboratory/DuAEF_Duik/tree/d2b930ba22a2e11cf4f77af97a232182f62cf0be/Release/Duik

**Comment by kotydwa76** [comment]
> These alerts are there because the project was rigged with Duik 15. older versions are there: https://github.com/RxLaboratory/DuAEF_Duik/tree/d2b930ba22a2e11cf4f77af97a232182f62cf0be/Release/Duik
Everything in projects was rigged with Bassel version I'm damn sure. We've been even talking about some issues with Pop-up window, year ago.

**Comment by kotydwa76** [comment]
I tried different versions I used before like 16,2.16 and no matter what - it crashes whenever i click "Autorig"
