### ISSUE TITLE
Goal-Checkbox

### ISSUE THREAD

**Issue by Mitsukatsu** [RxLaboratory/DuAEF_Duik#872]
Hi there, 
I love duik bassel2 and the passion and work you put into it, thanks for that!

in my latest character rig i wanted to make the hand-rotation follow the arm and searched for the goal-checkbox. When i coudn't find it i read that you decided to not include it in duik anymore. 
I found a workaround, but that didn't work like the classical goal-option either (making a null, linking it to the forearm, linking the hand to the null, add expression "value + pickWhipToTheControllerRotation") - now the hand followed the arm but i couldn't rotate the hand seperately with the controller  anymore...
I also read some comments of other duik users who were asking for a solution frequently.

please include the "goal" option again. i guess that would be the easiest and most user-friendly solution.

alternatively:  when i used duik earlier, there was still the goal-option included - i think it updated by itself to a version where it was no longer included. which version was the latest on where i can find the goal? so i can downgrade again

best regards, 
Frauke

**Comment by Nico-Duduf** [comment]
Hi,
The *goal* checkboxes have all been removed because they can be easily replaced by orientation constraints.

If you want the hand to stay aligned to the forearm, add an orientation constraint and select the forearm.
If you need to still be able to control it from the controller, add another orientation constraint and select the controller.
Etc.

;)

**Comment by Mitsukatsu** [comment]
thank you for your reply, but i still couldn't figure it out.
sorry, this is the first time i use the constraints and have no idea ow to use them. also i coudn't find much help on youtube.

i have one arm-artwork with 3 bones, one seperate hand-artwork and a controller for that.
could you clarify where the orientation constraint goes to? i tried to put it on the hand artwork and select under "constraint to" -> forearm-bone. 
this didn't work. I also tried to constrain it to other bones or the arm-artwork but that didn't work either or made very strange results.
