### ISSUE TITLE
duik Bassel suddenly won't add bones and existing bones are not working

### ISSUE THREAD

**Issue by justdoitx5** [RxLaboratory/DuAEF_Duik#875]
In the middle of my project after I rigged multiple characters with bones suddenly the bones started to not work and showed expression errors 

I tried to add more bones it worked at first but then now even in a new project when i try to create bones it stucks in "Magic is happening" window 

I tried uninstalling and fixing and still, it doesn't work.

all my characters and ruined I really need help

i will leave some of the expressions errors that appeared all around my project in the bones and layers

![Screenshot_1](https://user-images.githubusercontent.com/48094603/143665387-69e5e8dc-4a06-4188-b7f2-284ea2df6069.png)
![Screenshot_2](https://user-images.githubusercontent.com/48094603/143665388-dfccfe27-0d80-4e2c-8e19-e00aea0aee11.png)
![Screenshot_3](https://user-images.githubusercontent.com/48094603/143671581-38a44039-2e06-485f-9234-ddc94071f1f0.png)

windows 10
after effects 2022 also happened on 2020

**Comment by Nico-Duduf** [comment]
Hi,

sorry for the late reply ; can you try the "fix/uninstall" procedure described there: http://duik.rxlab.guide/install-duik.html#fix-uninstall-duik ?
This may fix the issue, which looks like the effect files used by Duik have been corrupt somehow

**Comment by justdoitx5** [comment]
The problem has been fixed
i think what caused the problem is that i would shut of the bones layers
after i create them
i recommend lowering the opacity or decrease the size if the icon instead
of turning them off
