### ISSUE TITLE
Zero Button missing Duik Bassel 2

### ISSUE THREAD

**Issue by Kazryugo** [RxLaboratory/DuAEF_Duik#876]
**Describe the bug**
I cant find de Zero Button on the ui pannel of the script. I toggled from rookie to expert, standard even God, but 
I wasn't able to find it. Can anyone, save me? 

**Screenshots**
<img width="427" alt="Captura de Tela 2021-11-28 às 14 20 31" src="https://user-images.githubusercontent.com/95182612/143778848-3f991197-70d9-4118-904b-4ebecdb858e5.png">

<img width="431" alt="Captura de Tela 2021-11-28 às 14 22 34" src="https://user-images.githubusercontent.com/95182612/143778881-7817fac2-3063-47d9-b92a-605e57f053e5.png">

**System :**
 - OS: MAC
 - Version of After Effects: 22.0.1
 - Version of Duik: 16.2.30

**Comment by Nico-Duduf** [comment]
it's in the rigging/constraints panel, as stated in the doc

**Comment by Kazryugo** [comment]
Thank you so much, Nico
