### ISSUE TITLE
Impossible to execute the script at the line 39994

### ISSUE THREAD

**Issue by BennBech** [RxLaboratory/DuAEF_Duik#879]
**Describe the bug**
When I launch the Duik Bassel.2 script in After Effects (or any other panel script) a box appear "impossible d'exécuter le script à la ligne 39994. null n'est pas un objet“. Same Issue after having updated After effects and tried to install an older version.

**To Reproduce**
1. Copy the Duik Bassel.2.jsx file in the ScriptUI Panels folder of After effects
2. launch it from the script menu or the window menu  

**Error description, if any**
File: Duik Bassel.2.jsx
Line number:39994
Error message: "impossible d'exécuter le script à la ligne 39994. null n'est pas un objet."

**System (please complete the following information):**
 - OS: macOS Big Sur
 - Version of After Effects: 22.0.1
 - Version of Duik: Duik_Bassel.2_16.2.30
 
<img width="402" alt="Capture d’écran 2021-12-08 à 16 24 14" src="https://user-images.githubusercontent.com/95763410/145234811-b98ca311-3cbf-4233-a047-9e4004b53111.png">

**Comment by Nico-Duduf** [comment]
This looks like an issue with the file access to your documents folder (Duik can't read the settings file).

You can try to:
- Remove the "Duik Bassel" folder you may find in your "documents" folder
- Try the "Fix/uninstall" procedure there: http://duik.rxlab.guide/install-duik.html#fix-uninstall-duik
- Deactivate any sync tool you may have running on the documents folder (like one-drive, drop box, or the same from Mac (I don't know its name)

**Comment by BennBech** [comment]
Well, the first step have fixed the problem...
Thank you, I have learned a very usefull tip.
