### ISSUE TITLE
unable to execute script at line 39994. null is not an object

### ISSUE THREAD

**Issue by Mahantesh18** [RxLaboratory/DuAEF_Duik#882]
![IMG20220122073119](https://user-images.githubusercontent.com/98172878/150620554-426cff0e-9bc1-43c6-bf58-b8cdf57bf5e9.jpg)
**Describe the bug**

**To Reproduce**
1. Opening duik bassel
2. 
3. 

**Error description, if any**
File: 
Line number:39994
Error message: unable to execute script at line 39994. null is not an object

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Version of After Effects: 2022
 - Version of Duik:2_16.2.30

**Additional context**

![IMG-20220121-WA0004](https://user-images.githubusercontent.com/98172878/150575861-1daff29b-93c4-4411-b8d6-28011e5b513a.jpeg)

**Comment by Nico-Duduf** [comment]
- Update Duik
- Try to remove the "Duik Bassel.2" folder in your documents folder then restart
- Try this procedure: http://duik.rxlab.guide/install-duik.html#fix-uninstall-duik
