### ISSUE TITLE
AutoRig a leg gives an error on an Undefined element in a leg

### ISSUE THREAD

**Issue by FloridaGames** [RxLaboratory/DuAEF_Duik#890]
Character is setup. Leg ready to rig. Autorig gives this error.

**To Reproduce**
1. Select the Leg Bones
2. On Links and Constraints use the Auto Rig option
3. Gives an Error at line 40316, undefined is not an object

**Error description, if any**
File:  Duik%20Angela.jsx
Line number: 40316
Error message: undefined is not an obect

**Expected behavior**
Same steps for arms work fine. Here an expression error occurs.

**Screenshots**
![image](https://user-images.githubusercontent.com/100477809/158840739-adc60010-f489-451f-940f-cf244d46c52c.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 2021, also occurs in 2022
 - Version of Duik: Angela Alpha10

**Additional context**
Doing the AutoRig from the bones tab has the same result.
Opening up the expressions it seems to be in 'rotation'.

**Comment by Nico-Duduf** [comment]
Thanks for the feedback, fixed in Alpha 11 available in a couple of days
