### ISSUE TITLE
Duik Bassel plugin

### ISSUE THREAD

**Issue by YuliiaLysenko** [RxLaboratory/DuAEF_Duik#891]
There is no import-export tab in DUIK BASSEL 2 plugin for After effects after installation.

I want  that tab will appear, like on picture there http://duik.rxlab.guide/rigging-tools.html

I am just user and do not know what can i do/

**Additional context**
![image](https://user-images.githubusercontent.com/40669142/160233849-b5b28764-0089-417c-8a7b-0e630cba8336.png).

**Comment by Nico-Duduf** [comment]
Hi,
The page you linked is the tools panel, which has an import animation and an export animation tools, if and only if you switch the UI mode to standard/expert/god in the settings of Duik: http://duik.rxlab.guide/settings.html

If you need other import/export tools, some of which were in older versions of Duik, we've assembled them in another script, DuIO: https://rxlaboratory.org/tools/duio/
